### ISSUE TITLE
Link error: ___llvm_profile_runtime_user in EnvironmentStorage.o

### ISSUE THREAD

**Issue by JetForMe** [Wouter01/SwiftUI-Macros#1]
I'm not sure if this is a bug in Xcode 15b4, or something to do with this macro library, but I get this after adding it to my Xcode project (an iOS app targeting iOS 16+), during the link phase:

```
ld: Undefined symbols:
  ___llvm_profile_runtime, referenced from:
      ___llvm_profile_runtime_user in EnvironmentStorage.o
      ___llvm_profile_runtime_user in SwiftSyntaxMacros.o
      ___llvm_profile_runtime_user in SwiftSyntax.o
      ___llvm_profile_runtime_user in SwiftDiagnostics.o
      ___llvm_profile_runtime_user in SwiftParser.o
      ___llvm_profile_runtime_user in SwiftBasicFormat.o
      ___llvm_profile_runtime_user in SwiftParserDiagnostics.o
```

**Comment by Wouter01** [comment]
I tried reproducing this but I was not able to. Could you create a test project and see if the issue also occurs there?

**Comment by JetForMe** [comment]
This project exhibits the behavior. I created a new iOS project from the App template, added the SwiftUI macros dependency, and built. It seemed to build fine, although I had interrupted the first build when I noticed that the selected target wasn't the simulator. I switched to an iPhone SE 3rd gen 16.0 sim, and built, and it built successfully but suspiciously quickly.

I then set the deployment target to iOS 16.0, rebuilt, and it got the link error. Then I set the deployment target back to iOS 17, and it still gets the error.

[TestMacro.zip](https://github.com/Wouter01/SwiftUI-Macros/files/12044384/TestMacro.zip)

**Comment by Wouter01** [comment]
Thank you, I was able to reproduce the error. I had a closer look and it looks like this is an issue with the new linker, as multiple packages are having [issues](https://github.com/golang/go/issues/61229). I made a new macro (with Xcode File > New > Package > Macro) and building with the provided client scheme gives the same error, so I will assume this is a bug in Xcode or the linker that will get fixed

**Comment by JetForMe** [comment]
Okay, thanks for confirming. I'll write a radar.

**Comment by JetForMe** [comment]
FYI, turning off code coverage in the test plan will allow the build to proceed.
