### ISSUE TITLE
Error on CI: Target 'SwiftUIMacrosImpl' must be enabled before it can be used

### ISSUE THREAD

**Issue by sisoje** [Wouter01/SwiftUI-Macros#2]
I noticed an error on our CI.
We use bitbucket. This is the error: `Target 'SwiftUIMacrosImpl' must be enabled before it can be used`
Is there something to be done in the package itself, or we need to fix CI on our end?

**Comment by Wouter01** [comment]
As macros alter source code, Xcode requires you to allow them first. It looks like there is a flag you can set so this manual approval is not needed (see [here](https://stackoverflow.com/questions/77267883/how-do-i-trust-a-swift-macro-target-for-xcode-cloud-builds))
