### ISSUE TITLE
Add generated View modifiers for the environment values

### ISSUE THREAD

**Issue by kristofkalai** [Wouter01/SwiftUI-Macros#3]
Hi! 👋 

I have used this library recently, and it does a fantastic job! 🚀 However, I think it could be improved a little bit. Let me explain my idea / problem.

# Problem

Currently the user of the library either uses the .environment modifier for the generated environment values, or they can write for themselves the View modifier. It requires more boilerplate to be written, which should be more simple to do.

## Example

Let's say I have the following:

```swift
@EnvironmentStorage
extension EnvironmentValues {
    var envFont: Font = .largeTitle
}
```

I can use it like:

```swift
TestText(text: "Hello, world!")
    .environment(\.envFont, .title)
```

Which is fine, but most of the developers tend to write a "wrapper method" for every environment value. So I can write manually:

```swift
extension View {
    func envFont(_ envFont: Font) -> some View {
        environment(\.envFont, envFont)
    }
}
```

With this the mentioned code would look like this:

```swift
TestText(text: "Hello, world!")
    .envFont(.title)
```

Which is more readable and concise, while enables better autocomplete.

## Solution

For every environment value the library should generate a method, like this:

```swift
extension View {
    func <environmentValueName>(_ <environmentValueName>: <environmentValueType>) -> some View {
        environment(\.<environmentValueName>, <environmentValueName>)
    }
}
```

Unfortunately I'm not proficient in Swift macros - is it even feasible to implement?
Does it have any technical limitation?
Thanks!

**Comment by Wouter01** [comment]
Unfortunately, such a thing wouldn't be possible to add, at least automatically. The `EnvironmentStorage` macro is attached to `EnvironmentStorage` and can therefore only expand that type (or its subtypes). It cannot extend the `View` type, because it doesn't have "access" to it.

**Comment by kristofkalai** [comment]
I see @Wouter01 , thanks for the explanation! I was thinking about something similar when I mentioned technical limitations 😞
