### ISSUE TITLE
`EnvironmentKey` types should be `private`.

### ISSUE THREAD

**Issue by JessyCatterwaul** [Wouter01/SwiftUI-Macros#4]
For example, none of the ones Apple provides are accessible.

**Comment by Wouter01** [comment]
Making them private seems reasonable. Would this give any benefits over keeping them `internal`?

**Comment by JessyCatterwaul** [comment]
> Would this give any benefits over keeping them `internal`?

That's a religious argument 😇, so do what you like—either seems an improvement, to me. FWIW, [the official example](https://developer.apple.com/documentation/swiftui/environmentkey) is `private`.

**Comment by Wouter01** [comment]
Clear! I will update the package tomorrow.

**Comment by Wouter01** [comment]
Fixed!
