### ISSUE TITLE
There is no option for set-only values.

### ISSUE THREAD

**Issue by JessyCatterwaul** [Wouter01/SwiftUI-Macros#5]
We don't need to [modify](https://developer.apple.com/documentation/swiftui/view/environment(_:_:)) all environment values. Sometimes having the default be readable is sufficient.

**Comment by Wouter01** [comment]
How would you use a environment value that isn't writable? Wouldn't that always give the default value?
Or, are you referring to a private setter and a public getter? This is likely what SwiftUI also does under the hood for its built-in environmentkeys that aren't settable. You should be able to do this with this package too:

```swift
@EnvironmentStorage 
extension EnvironmentValues {
    public private(set) var test: Bool = false
}
```

**Comment by JessyCatterwaul** [comment]
> Wouldn't that always give the default value?

Yes. As I said, sometimes you just need an immutable singleton accessible in views—the Environment is the canonical place for them. For example, this can't change:

```swift
extension EnvironmentValues {
  private enum MetalDeviceKey: EnvironmentKey {
    static var defaultValue: some MTLDevice { MTLCreateSystemDefaultDevice()! }
  }

  var metalDevice: any MTLDevice { self[MetalDeviceKey.self] }
}
```

**Comment by Wouter01** [comment]
I see!

I might be wrong, but if you want to use singletons in the environment, EnvironmentKeys might not be needed. As in, you should be able to do

```swift
extension EnvironmentValues {
  var metalDevice: some MTLDevice { MTLCreateSystemDefaultDevice()! }
}
```
Would such a thing work for you?

**Comment by JessyCatterwaul** [comment]
> Would such a thing work for you?

Not that exactly, but there are of course many options. `EnvironmentValues` just canonicalized how to pretend like you have dependency injection of instance properties, so I switched to it 5 years ago.

I have no idea how you'd find a list of which environment values SwiftUI provides are read-only, to see the precedent. They'll all generate the same error:

> **Key path value type 'KeyPath<EnvironmentValues, Whatever>' cannot be converted to contextual type 'WritableKeyPath<EnvironmentValues, Whatever>'**

E.g. 

```swift
.environment(\.pixelLength, 1)
```

**Comment by Wouter01** [comment]
> I have no idea how you'd find a list of which environment values SwiftUI provides are read-only, to see the precedent. They'll all generate the same error:
> 
> > **Key path value type 'KeyPath<EnvironmentValues, Whatever>' cannot be converted to contextual type 'WritableKeyPath<EnvironmentValues, Whatever>'**

This error occurs when the computed property in `EnvironmentValues` has no (accessible) setter. I have checked with both examples from above and they both will show this error.
